version: '2.2'

services:
  nginx:
    image: nginx:alpine
    restart: always
    entrypoint: sh
    command:
      - -c
      - envsubst '$${DOCUMENT_ROOT}' < /etc/nginx/conf.d/default.conf.tpl | tee /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)
      - traefik.http.services.nginx.loadbalancer.server.port=80
    volumes:
      - ./config/nginx/node.conf:/etc/nginx/conf.d/default.conf.tpl:ro
    volumes_from:
      - node

  node:
    image: node:12-alpine
    restart: always
    working_dir: /node
    volumes:
      - ${PATH_NODE}:/node
      - ${HOSTS_FILE}:/etc/hosts
    tty: true
